version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BreathTestDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test1234
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: BreathTestDB
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
